---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
  namespace: default
  annotations:
    kubernetes.io/change-cause: Creation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-echo
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
      - name: http-echo
        image: sgaunet/http-echo:0.2.0
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 10
        # envFrom:
        #   - configMapRef:
        #       name: cm-http-echo
        resources:
          requests:
            memory: "32Mi"
            cpu: "200m"
          limits:
            memory: "32Mi"
            cpu: "200m"
        # imagePullPolicy: Always

      restartPolicy: Always
