kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node=worker_1,ingress-ready=true"
        extraMounts:
          - hostPath: ./data
        containerPath: /tmp/data
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    # - containerPort: 443
    #   hostPort: 443
    #   protocol: TCP
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node=worker_2"
        extraMounts:
          - hostPath: ./data
        containerPath: /tmp/data
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node=worker_3"
        extraMounts:
          - hostPath: ./data
        containerPath: /tmp/data