
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-echo
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: http-echo
            port:
              number: 8080
