image:
  pullPolicy: "Always"
  tag: "latest-amd64"
  image: "ghcr.io/sgaunet/kubetrainer"

configuration:
  DB_DSN: "postgres://kubetrainer:kubetrainer@postgresql:5432/kubetrainer?sslmode=disable"
  REDIS_DSN: "redis://redis-master:6379"
  REDIS_MAXSTREAMLENGTH: 1000
  REDIS_STREAMGROUP: "kubetrainer"
  REDIS_STREAMNAME: "kubetrainer"
  CONSUMER_MODE: true
  PRODUCER_DATA_SIZE_BYTES: "1073741824" # 1GB

command: 
  - kubetrainer
  - -consumer