# https://taskfile.dev
version: '3'
tasks:
  default:
    desc: "list all tasks"
    cmds:
      - task -a

  setup-helm-diff:
    desc: "ensure helm-diff plugin is installed and compatible with Helm v4"
    cmds:
      - |
        # Check if helm-diff is installed
        if helm plugin list | grep -q "^diff"; then
          DIFF_VERSION=$(helm plugin list | grep "^diff" | awk '{print $2}')
          echo "helm-diff version $DIFF_VERSION is installed"

          # Check if version is < 3.10.0 (incompatible with Helm v4)
          if [ "$(printf '%s\n' "3.10.0" "$DIFF_VERSION" | sort -V | head -n1)" != "3.10.0" ]; then
            echo "helm-diff version $DIFF_VERSION is incompatible with Helm v4, upgrading..."
            helm plugin uninstall diff
            helm plugin install https://github.com/databus23/helm-diff --verify=false
            echo "helm-diff upgraded successfully"
          else
            echo "helm-diff is compatible with Helm v4"
          fi
        else
          echo "Installing helm-diff plugin..."
          helm plugin install https://github.com/databus23/helm-diff --verify=false
          echo "helm-diff installed successfully"
        fi
    silent: false

  install:
    desc: "install kubetrainer"
    cmds:
      - task: setup-helm-diff
      - echo "Deploying Redis from raw manifest..."
      - kubectl apply -f redis.yaml
      - echo "Waiting for Redis to be ready..."
      - kubectl wait --for=condition=available --timeout=120s deployment/redis-master -n default
      - helmfile apply

  port-forward-ihm:
    desc: "port forward kubetrainer"
    cmds:
      - echo "kubetrainer is available at http://localhost:3001"
      - kubectl port-forward --namespace default service/kubetrainer 3001:3000